### PR TITLE
Updating URL on click or enter

### LINKED ISSUE #17: Entering an image URL should update the page URL
At least in the hosted version, if I go to: 

http://openseadragon.github.io/openseadragonizer/

...and enter foo.jpg into the box, the URL of the page should update to: 

http://openseadragon.github.io/openseadragonizer/?img=foo.jpg

...so I can then share it with my friends.

### PR DESCRIPTION
**Pull request by TMUND**
Fixes #17

### CODE REVIEW

**Comment by iangilman** [comment]
Looks good to me... @avandecreme does this look good to you?

**Comment by avandecreme** [comment]
It seems to work but I am surprised it does.
Shouldn't it be
```javascript
location.href += '?img=' + urlElt.value;
```
(Notice += instead of =)

**Comment by iangilman** [comment]
I believe when you set `location.href` it's just the same as when you click on a link...all URLs are considered relative to the current location. That's why `=` works (though I imagine `+=` would work too).

**Comment by avandecreme** [comment]
Alright, it is probably safer to use `=` then.

**Comment by iangilman** [comment]
I've just done some experimentation, and I think `=` is better. If the URL already has a query string and you do `= '?foo=1'`, it replaces the query string. With `+=` it actually adds the new query string to the old one.

**Comment by avandecreme** [comment]
Yes, that is what I thought. Merged :) Thanks @TMUND

**Comment by iangilman** [comment]
Excellent. I'll handle publishing it to the site.

**Comment by iangilman** [comment]
Deployed to http://openseadragon.github.io/openseadragonizer/ !

**Pull request merged**
