### PR TITLE
Add a spinner

### PR DESCRIPTION
**Pull request by avandecreme**

### CODE REVIEW

**Comment by iangilman** [comment]
Lovely! You'll deploy (or you've already deployed)?

**Comment by iangilman** [comment]
I've taken the liberty of deleting the branch...

**Comment by avandecreme** [comment]
Deployed on the website.
Working on packaging the extensions.

**Comment by avandecreme** [comment]
And extensions uploaded to the stores. As usual, Firefox will take a while...

**Comment by iangilman** [comment]
Excellent... looks like the Firefox one has been approved too :)

**Pull request merged**
