### PR TITLE
Imagetilesource

### PR DESCRIPTION
**Pull request by avandecreme**
Still need to handle error from OSD with the tile-load-failed event.
Open for discussion in the mean time.

### CODE REVIEW

**Comment by iangilman** [comment]
Seems good to me...

**Comment by avandecreme** [comment]
The tile-load-failed event can't actually be fired with the ImageTileSource.
I can't actually think of any failure we could have in OSD since OSD is started only when the image has been entirely loaded. So I just don't listen to any failure event.

**Comment by iangilman** [comment]
Makes sense. 

The new code is looking good. One question: why the `encoded` URL param?

**Comment by avandecreme** [comment]
>One question: why the encoded URL param? 

Because if the image url has parameters, we need to encode it to properly distinguish it from the extension own's parameters.
However, I wanted to leave the capability to use non encoded URL for easier sharing of an openseadragonized image: you just need to post a link to openseadragonize/index.html?url=theURL 99% of the time.

**Comment by iangilman** [comment]
Makes sense. I wonder if it might be worth doing some auto detection...if there is a % in the URL, assume it's decoded, and if there isn't, assume it's not. We could still have the `encoded` param as an override if need be.

**Pull request merged**
